# Site settings
title: Probe Dock
email: contact@probe-dock.io
description: > # this means to ignore newlines until "baseurl:"
  Probe Dock is a test tracking and analysis tool.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://probe-dock.io" # the base hostname & protocol for your site
twitter_username: ProbeDock
github_username:  probe-dock

# Build settings
markdown: kramdown
