# Site settings
title: ProbeDock
email: contact@probedock.io
description: > # this means to ignore newlines until "baseurl:"
  ProbeDock is a test tracking and analysis tool.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://probe-dock.io" # the base hostname & protocol for your site
twitter_username: ProbeDock
github_username:  probedock

# Build settings
markdown: kramdown
