# Site settings
title: Probe Dock
email: contact@probedock.io
description: > # this means to ignore newlines until "baseurl:"
  ProbeDock is a test tracking and analysis tool.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://probedock.io" # the base hostname & protocol for your site

# Author name shown for a post when no author is specified
default_author: Probe Dock

paginate: 6
paginate_path: "/blog/:num/"

permalink: "/blog/:categories/:year/:month/:day/:title/"

# Social
twitter_username: ProbeDock
github_username:  probedock
disqus_shortname: probedock

# Build settings
markdown: kramdown
exclude:
  - local
  - assets/less
  - assets/plugins/font-awesome/less
  - assets/plugins/font-awesome/sass
